checkout: null
commit: 263046641a66377eb62ca19c6cbb54f6281848bb
context:
  _copy_without_render:
  - .github/**/*.jinja
  _dev_requirements:
    bump2version: '>=1.0.1'
    generate-changelog: '>=0.7.6'
    git-fame: '>=1.12.2'
    pip-tools: ''
  _docs_requirements: {}
  _prod_requirements:
    environs: '>=9.3.5'
  _test_requirements:
    coverage: ~=6.1.2
    poetry: ~=1.3.2
    pre-commit: ~=2.15.0
    pytest: ~=6.0.0
    pytest-cov: ~=3.0.0
  author: SpazioDati s.r.l.
  email: berardi@spaziodati.eu
  friendly_name: Dandelion
  github_user: giacbrd
  packaging_tool: pip/setuptools
  project_name: python-dandelion-eu
  project_short_description: Connect to the dandelion.eu API in a very pythonic way!
  project_slug: dandelion
  version: 0.3.2
directory: null
merge_strategies:
  '*': do-not-merge
no_input: false
overwrite: []
overwrite_exclude: []
password: null
skip_generation: []
skip_hooks: false
skip_if_file_exists: false
template: ../datascience-cookiecomposer-templates/cookiecutter-boilerplate
