repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        additional_dependencies: ["toml"]
        args: ["--profile", "black"]
  - repo: https://github.com/python/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
        exclude: test.*
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        exclude: test.*
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: "^tests/resources/"
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: requirements-txt-fixer
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        additional_dependencies: ["gibberish-detector"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.0
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        additional_dependencies: ["pydantic", "toml", "types-all"]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: [--skip, "B101,B104", --recursive, "-q"]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: test.*
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        exclude: test.*
        additional_dependencies: [toml, tomli]
  - repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.1
    hooks:
      - id: darglint
        exclude: test.*
        args:
          - -v 2
          - "--message-template={path}:{line} in `{obj}`:\n        {msg_id}: {msg}"
          - --strictness=short
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0  # or master if you're bold
    hooks:
      - id: interrogate
        exclude: test.*
  - repo: local
    hooks:
      - id: check-dependencies
        name: check-dependencies
        language: python
        entry: make -C requirements all
        files: ^requirements.*?\.(in|txt)$
        pass_filenames: false
        additional_dependencies:
          - pip-tools
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.21.0
    hooks:
      - id: check-azure-pipelines
