language: python
python:
- '2.7'
- '3.3'
install:
- pip install .
- pip install -r requirements-dev.txt
- pip install coveralls
script: coverage run --source=dandelion --branch `which nosetests` tests/*
env:
  global:
  - secure: R/fXB/RCiSBEjJFXnPsX3b++j0J+oS4V+7nX+GCENiIha1rnL9iwY42PVY6LxKiBEi/3rLOm4fchk/W+v2+0BP4ULbTTtH13CmXtLMIr+SVCAI03E6rMppUOp+zpLnUahSeufhQYPwgq12Bl9lYJN5p8uis4D6N2gdCHwJjG4CA=
  - secure: slI5VBvkslKCD3uvgEeXZSJDWJRvKUwX/jMV2i1qrjPlD4Ur+F6fS51mV2aQ8tbXBc6dyFn73N5tJyvv//C5cOGVWrOV7mzAMSQ75Ati764MyS95k0PG1PwbZjLNShl18JKpjXt+jUynEPzTq74Pg4L6CeLsWhkbR5R9TSfukU8=
after_success:
  coveralls
