variables:
  - template: global-variables/auto-versioning.yml@templates
    parameters:
      majorVersion: "1" # Change this version to bump major version
      minorVersion: "0" # Change this version to bump minor version
  - template: global-variables/common.yml@templates

resources:
  repositories:
    - repository: templates
      type: github
      name: 'ch-robinson-internal/DataScience.Pipeline.Library'
      # if for migration safety, you can put a git tag from
      # the DataScience.Pipeline.Library repo here
      # ref: refs/tags/1.0.46, etc.
      ref: 'refs/heads/main'
      endpoint: 'GitHub - CH Robinson Internal-Data and Analytics Partners'

name: $(Date:yyyyMMdd)$(Rev:.r)

pool:
  name: 'devops-datascience-docker-pool'

# trigger this pipeline on change to main
trigger:
  batch: true
  branches:
    include:
      - 'main'
      - 'master'

# Trigger this build on prs to main
pr:
  - main
  - master

jobs:
# test the poetry python module pipeline
- template: /pipelines/python-module.yml@templates
  parameters:
    releaseVersion: $(releaseVersion)
    moduleName: 'dandelion'
    sonarName: 'dandelion'
    coverageDirectory: 'dandelion'
    sourceDirectory: '.'
    poetryPackage: false
    unitTestDirectory: 'test'
    buildContainerImage: 'artifactory.chrobinson.com:5050/datascience/python38-build-image:latest'

#- template: /git/tag-and-release.yml@templates
#  parameters:
#    dependsOn:
#      - UnitTest
#      - FunctionalTest
#    tag: $(releaseVersion)
#    releaseNotesInline: "Release dandelion: $(releaseVersion)"
